config/routes.rb
PhysicsOnYourPhone::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :data_sets, only: [:create, :destroy, :show]
  
  root to: 'static_pages#home'
  match 'help', to: 'static_pages#help'
  match 'about', to: 'static_pages#about'
  match 'contact', to: 'static_pages#contact'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  

end

app/models/data_set.rb
# == Schema Information
#
# Table name: data_sets
#
#  id          :integer          not null, primary key
#  description :string(255)
#  ydata       :binary
#  tdata       :binary
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class DataSet < ActiveRecord::Base
  attr_accessible :description, :tdata, :ydata
  belongs_to :user
  
  validates :user_id, presence: true
  
  # Maximum data length is 1 minute at 100 Hz stored as single precision float
  validates :ydata, presence: true, length: { maximum: 4*60*100}
  validates :tdata, presence: true, length: { maximum: 4*60*100}
  
  default_scope order: 'data_sets.created_at DESC'
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :data_sets, dependent: :destroy
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum:50 }
  
  # See www.rubular.com for a Ruby Regexp Tutorial
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
    
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
   
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  before_filter :signed_in_user

  def create
    ydata = params[:data_set][:ydata].split(",").map { |s| s.to_f }.pack("f*")
    tdata = params[:data_set][:tdata].split(",").map { |s| s.to_f }.pack("f*")
    @data_set = current_user.data_sets.build(description: params[:data_set][:description],
      tdata: tdata, ydata: ydata)
    if @data_set.save
      flash[:success] = "Data set created!"
      redirect_to data_set_url(@data_set)
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end
  
  def show
    @data_set = DataSet.find(params[:id])
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  def destroy
      sign_out
      redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @data_set = current_user.data_sets.build if signed_in?
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:show, :edit, :update, :index, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  before_filter :non_signed_in_user, only: [:new, :create]
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @data_sets = @user.data_sets.paginate(page: params[:page])
  end
  
  def edit
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def update
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated"
        sign_in @user
        redirect_to @user
      else
        render 'edit'
      end
  end
  
  def destroy
    if params[:id].to_i != current_user.id
      User.find(params[:id]).destroy
      flash[:success] = "User destroyed."
    else
     flash[:error] = "Cannot delete current admin users"
    end
    redirect_to users_url
  end
  
  
  
  private
  
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to (root_path) unless current_user?(@user)
    end
        
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
  
    def non_signed_in_user
      redirect_to(root_path) unless !signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # returns full title on a per-page basis.
  
  def full_title(page_title)
    base_title = "Physics On Your Phone"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/data_set_helper.rb
#require "gchart"
#require "gruff"
require "flotilla-rails"

module DataSetHelper
  def graph_for(dataset, options = { size: 300 })
    ydata = dataset[:ydata].unpack("f*")
    tdata = dataset[:tdata].unpack("f*")
    line_width = 10
    color = 'red'
    title = "Chart Title"
    point_size = 3
    #chart_url = Gchart.line(:data => [tdata, ydata], 
    #                          :linewidth => line_width, 
    #                          :line_colors => color, 
    #                          :title => title, 
    #                          :point_size => point_size)
    
    
    chart("graph", { "Store 1" => { :collection => @store_one, :x => :date, :y => :sales } }, { :js_includes => false })
    
    
    image_tag(chart_url, alt: dataset.description, class: "data-graph")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  end
    
  def sign_out
    self.current_user = nil
    session[:return_to]=nil
    session.delete(:return_to)
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    # The following line does not work (hence moved the code to the sign_out method)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = nil
    session[:return_to] = request.url
  end

    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 100 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/data_sets/_data_set.html.erb
<li>
  <span class="description"><%= link_to data_set.description, data_set %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(data_set.created_at) %> ago.
  </span>
</li>

app/views/data_sets/_display_graph.html.erb
<%= javascript_include_tag  "jquery", "jquery.flot" %>

<div id="placeholder" style="width:600px;height:300px;"></div>

<script type="text/javascript">
$(function () {
    var d2 = [[0, 3], [4, 8], [8, 5], [9, 13]];

    // a null signifies separate line segments
    var d3 = [[0, 12], [7, 12], null, [7, 2.5], [12, 2.5]];
    
    $.plot($("#placeholder"), [ d2, d3 ]);
});
</script>

app/views/data_sets/show.html.erb
<%= javascript_include_tag  "jquery", "jquery.flot" %>
<% provide(:title, "Data") %>


<h1>
	<%= @data_set.description %>
</h1>
<span class="data"><%= @data_set.tdata.unpack("f*").to_s %></span>
<span class="data"><%= @data_set.ydata.unpack("f*").to_s %></span>

<div id="placeholder" style="width:600px;height:300px;"></div>

<script type="text/javascript">
$(function () {
    tdata = <%= @data_set.tdata.unpack("f*") %>;
	ydata = <%= @data_set.ydata.unpack("f*") %>;
	
	var typairs = [];
	for (var i=0; i < tdata.length; i++)
		typairs.push([tdata[i],ydata[i]]);
    
    $.plot($("#placeholder"), [ typairs ]);
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>&copy;2013 by Jen Dobson</p>
</small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Physics on your Phone", root_path, id: "logo" %>
			<nav>

				<ul class="nav pull-right">
					<li><%= link_to "Home",    root_path %></li>
					<li><%= link_to "Help",    help_path %></li>
					<% if signed_in? %> 
					<li><%= link_to "Users", users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>

					<% else %>

					<li><%= link_to "Sign in", signin_path %></li>
					<% end %>  
				</ul>


			</nav>



		</div>

	</div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signin_id.html.erb
	<% if signed_in? %>
	<div class="container">
		<div id="signin-id">
			You are signed in as <%= link_to "#{current_user.name}", current_user %>.
		</div>
	</div>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
	<%= render 'layouts/signin_id'%>
    <div class="container">
	  <% flash.each do |key, value| %>
	    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	  <% end %>
      <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
	  <% if Rails.env.development? %>
	    <div id="request_data">
		  <ul>
			<li>format:<%= request.format %></li>
			<li>method:<%= request.method %></li>
			<li>sessions:<%= session[:return_to] %></li>
		  </ul>
	  	</div>
	  <% end %>
    </div>
  </body>
</html>

app/views/shared/_data_set_form.html.erb
<%= form_for(@data_set) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :description, placeholder: "Data set description..." %>
	<%= f.text_area :tdata, placeholder: "0, 1, 2, 3, 4" %>
	<%= f.text_area :ydata, placeholder: "0, 1, 2, 1, 0" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.data_sets.count, "Data set") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>
<h1>About Us</h1>
<p>
	Physics On Your Phone is a web-based learning tool to teach physics using mobile phone technology.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ferncliff Technologies about this project at
  <a href="http://fernclifftechnolgies.com/contact"> the Ferncliff Technologies contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>
<p>
	Thank you for visiting us.  We are currently under construction.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>

<% if signed_in? %>
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/data_set_form' %>
		</section>
	</aside>
</div>

<% else %>

<div class="center hero-unit">
	<h1>Physics On Your Phone</h1>
	<h2>
		This is the home page for Physics On Your Phone.  Thank you for visiting.  We are currently under construction.  
	</h2>
	<p>
		To learn more about our Motion Logger app, please click here:  <a href="http://motionlogger.fernclifftechnologies.com">Motion Logger App</a>
	</p>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= image_tag("physicsonyourphonestub.png", alt: "Physics On Your Phone") %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Retype Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %> 
	| <%= link_to "delete", user, method: :delete,
	data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">

		<%= form_for(@user) do |f| %>
		<%= render 'fields', f: f %>
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		<div id="edit_gravatar">
			<div id="egrav_imgdiv">
				<%= gravatar_for @user %>
			</div>
			<div id="egrav_linkdiv">
				<a href="http://gravatar.com/emails" target="_blank">Change Gravatar at Gravatar.com</a>
				<p>(This link will open in a new window.)</p>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
   	 <%= form_for(@user) do |f| %>
		  <%= render 'fields', f: f %>
	      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
	    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="span8">
		<% if @user.data_sets.any? %>
		<h3>Datasets (<%= @user.data_sets.count %>)</h3>
		<ol class="datasets">
			<%= render @data_sets %>
		</ol>
		<%= will_paginate @data_sets %>
		<% end %>
	</div>
</div>